"""add service history and maintenance

Revision ID: 08b9ee970a4d
Revises: af151aa44c7d
Create Date: 2026-08-17 23:41:39.978591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b9ee970a4d'
down_revision: Union[str, Sequence[str], None] = 'af151aa44c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('last_completed_date', sa.Date(), nullable=True),
    sa.Column('last_completed_mileage', sa.Integer(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('next_due_mileage', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_items_user_id'), 'maintenance_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_maintenance_items_vehicle_id'), 'maintenance_items', ['vehicle_id'], unique=False)
    op.create_table('service_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('garage', sa.String(length=160), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_records_service_date'), 'service_records', ['service_date'], unique=False)
    op.create_index(op.f('ix_service_records_user_id'), 'service_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_service_records_vehicle_id'), 'service_records', ['vehicle_id'], unique=False)
    op.create_table('service_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_record_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_record_id'], ['service_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_path')
    )
    op.create_index(op.f('ix_service_receipts_service_record_id'), 'service_receipts', ['service_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_receipts_service_record_id'), table_name='service_receipts')
    op.drop_table('service_receipts')
    op.drop_index(op.f('ix_service_records_vehicle_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_user_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_service_date'), table_name='service_records')
    op.drop_table('service_records')
    op.drop_index(op.f('ix_maintenance_items_vehicle_id'), table_name='maintenance_items')
    op.drop_index(op.f('ix_maintenance_items_user_id'), table_name='maintenance_items')
    op.drop_table('maintenance_items')
    # ### end Alembic commands ###
