"""add MOT history tables

Revision ID: 14adf7784e40
Revises: 8b36ce8c878e
Create Date: 2026-08-13 21:05:15.669110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14adf7784e40'
down_revision: Union[str, Sequence[str], None] = '8b36ce8c878e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mot_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('mot_test_number', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_source', sa.String(length=30), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('registration_at_time_of_test', sa.String(length=16), nullable=True),
    sa.Column('test_result', sa.String(length=20), nullable=True),
    sa.Column('odometer_value', sa.Integer(), nullable=True),
    sa.Column('odometer_unit', sa.String(length=10), nullable=True),
    sa.Column('odometer_result_type', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'mot_test_number', name='uq_mot_tests_vehicle_number')
    )
    op.create_index(op.f('ix_mot_tests_vehicle_id'), 'mot_tests', ['vehicle_id'], unique=False)
    op.create_table('mot_defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mot_test_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('dangerous', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mot_test_id'], ['mot_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mot_defects_mot_test_id'), 'mot_defects', ['mot_test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mot_defects_mot_test_id'), table_name='mot_defects')
    op.drop_table('mot_defects')
    op.drop_index(op.f('ix_mot_tests_vehicle_id'), table_name='mot_tests')
    op.drop_table('mot_tests')
    # ### end Alembic commands ###
