"""add reminder settings and dismissals

Revision ID: afcfe71f81c2
Revises: e2f3b91d9d2c
Create Date: 2026-08-24 13:37:04.083383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afcfe71f81c2'
down_revision: Union[str, Sequence[str], None] = 'e2f3b91d9d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_dismissals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reminder_key', sa.String(length=255), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reminder_key', name='uq_reminder_dismissal_user_key')
    )
    op.create_index(op.f('ix_reminder_dismissals_user_id'), 'reminder_dismissals', ['user_id'], unique=False)
    op.create_table('reminder_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mot_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('maintenance_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('due_soon_days', sa.Integer(), nullable=False),
    sa.Column('due_soon_miles', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_settings')
    op.drop_index(op.f('ix_reminder_dismissals_user_id'), table_name='reminder_dismissals')
    op.drop_table('reminder_dismissals')
    # ### end Alembic commands ###
