"""add vehicle check history

Revision ID: e2f3b91d9d2c
Revises: 08b9ee970a4d
Create Date: 2026-08-21 23:52:42.534023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f3b91d9d2c'
down_revision: Union[str, Sequence[str], None] = '08b9ee970a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_check_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=12), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('first_checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('check_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'registration', name='uq_vehicle_check_history_user_registration')
    )
    op.create_index(op.f('ix_vehicle_check_history_last_checked_at'), 'vehicle_check_history', ['last_checked_at'], unique=False)
    op.create_index(op.f('ix_vehicle_check_history_registration'), 'vehicle_check_history', ['registration'], unique=False)
    op.create_index(op.f('ix_vehicle_check_history_user_id'), 'vehicle_check_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_check_history_user_id'), table_name='vehicle_check_history')
    op.drop_index(op.f('ix_vehicle_check_history_registration'), table_name='vehicle_check_history')
    op.drop_index(op.f('ix_vehicle_check_history_last_checked_at'), table_name='vehicle_check_history')
    op.drop_table('vehicle_check_history')
    # ### end Alembic commands ###
